server:
  port: 8489
logging:
  config: classpath:logback-spring.xml

# feign开启断路配置
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 50000
  ConnectTimeout: 50000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #这样写eureka服务注册中心会显示项目名和端口号
    #instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9010/eureka/

spring:
  application:
    name: wj-dc-center
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: Asia/Shanghai

  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    # password: root # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.duoqio.boot.business
mapper:
  not-empty: true
  enum-as-simple-type: true
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  support-methods-arguments: true
  reasonable: falsetitle=Api


swagger:
  title:
  description: Api Documentation
  version: 1.0.0


  name: yangf
  url: http://127.0.0.1/
  email: alooa@qq.com


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: zc20200422 #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)

xcxwxpay:
  appid: wx4422e690d6579c2c
  secret: 222e0492ae62785ba93bb20eeba850e4
  mchid:
  key:

  projectEnv: dev
  serverDomain: https://127.0.0.1/api

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
#      - /deviceRegist
      - /userLogin
      - /userRegist




#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: jingxiangjia
#    username: root
#    password: root
#    #开启消息确认模式
#    publisher-confirms: true
#    #开启消息可达监听
#    publisher-returns: true
#    #防止不可达消息被删除
#    template:
#      #开启不可达消息不会被broker给删除
#      mandatory: true
#    # 消费配置
#    listener:
#      simple:
#        concurrency: 5
#        max-concurrency: 10
#        acknowledge-mode: manual
#        prefetch: 1
#        default-requeue-rejected: false
#    #设置连接超时
#    connection-timeout: 1000000

